owner: zerlio
repo: zerlio-status


sites:
  - name: App (Web)
    url: https://app.zerlio.com/
  - name: App API Health
    url: https://app.zerlio.com/api/v1/health

  - name: Beta (Web)
    url: https://beta.zerlio.com/
  - name: Beta API Health
    url: https://beta.zerlio.com/api/v1/health

  - name: Mail SMTP (587)
    check: tcp-ping
    url: mail.zerlio.com
    port: 587

status-website:
  cname: status.zerlio.com
  name: Zerlio Status
